# Generated by Django 5.2.12 on 2026-03-24 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndrologyLabTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='AT001', max_length=20, unique=True)),
                ('technician_license', models.CharField(blank=True, max_length=100, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=50)),
                ('can_perform_dna_frag', models.BooleanField(default=False, help_text='Authorized for Sperm DNA Fragmentation Indexing')),
                ('can_perform_cryo', models.BooleanField(default=True, help_text='Authorized to freeze and map semen samples')),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andrology_technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
