# Generated by Django 5.2.13 on 2026-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_andrologylabtechnician'),
    ]

    operations = [
        migrations.AddField(
            model_name='andrologylabtechnician',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
