# Generated by Django 5.2.12 on 2026-04-27 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductiveEndocrinologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='END001', max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('specialization', models.CharField(default='Reproductive Endocrinology & Infertility', max_length=100)),
                ('medical_license_no', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('biography', models.TextField(blank=True, null=True)),
                ('can_perform_egg_retrieval', models.BooleanField(default=True)),
                ('can_perform_embryo_transfer', models.BooleanField(default=True)),
                ('can_design_ivf_protocols', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endocrinologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
