# Generated by Django 5.2.13 on 2026-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_reproduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproductiveendocrinologistprofile',
            name='is_department_head',
            field=models.BooleanField(default=True),
        ),
    ]
