# Generated by Django 5.2.12 on 2026-03-14 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('GYN', 'Gynaecologist'), ('EMB', 'Embryologist'), ('ANE', 'Anesthesiologist'), ('NUR', 'Nurse'), ('PHA', 'Pharmacist'), ('TEC', 'Lab Technician'), ('REG', 'Registrar'), ('PAT', 'Patient'), ('DON', 'Donor'), ('HRM', 'HR Manager'), ('ADM', 'Admin')], default='PAT', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('department', models.CharField(blank=True, default='Administration', max_length=50)),
                ('access_level', models.PositiveSmallIntegerField(choices=[(1, 'viewer'), (2, 'Manager'), (3, 'Super Admin')], default=1)),
                ('is_notified_on_new_user', models.BooleanField(default=True)),
                ('last_system_audit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnesthesiologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='AN001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('medical_license_no', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_info', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anesth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmbryologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='EM001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('certification_body', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('can_perform_icsi', models.BooleanField(blank=True, default=False)),
                ('can_perform_biopsy', models.BooleanField(blank=True, default=False)),
                ('is_lab_director', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embryologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GynaecologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='DR001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('total_egg_retrievals', models.PositiveIntegerField(blank=True, default=0)),
                ('medical_license_no', models.CharField(blank=True, max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gynaec_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='NR001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('nursing_license_no', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_head_nurse', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='RG001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desk_location', models.CharField(blank=True, help_text='Eg: Main Entrance', max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('can_access_billing', models.BooleanField(default=True)),
                ('can_modify_patient_records', models.BooleanField(default=False, help_text='Usually restricted to medical staff')),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
