# Generated by Django 5.2.12 on 2026-03-24 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REC', 'Receptionist'), ('CCO', 'Clinical Counsellor'), ('FCO', 'Financial Counsellor'), ('GYN', 'Gynaecologist'), ('ANE', 'Anesthesiologist'), ('EMB', 'Embryologist'), ('NUR', 'Nurse'), ('PHA', 'Pharmacist'), ('TEC', 'Lab Technician'), ('AND', 'Andrology Lab Technician'), ('PAT', 'Patient'), ('HRM', 'HR Manager'), ('ADM', 'Admin')], default='PAT', max_length=3),
        ),
        migrations.CreateModel(
            name='ClinicalCounsellorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='CO001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=50)),
                ('specialization', models.CharField(default='Fertility & IVF Counseling', max_length=100)),
                ('years_of_exp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('department_head', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_counsellor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCounsellorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='FO001', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('can_approve_discounts', models.BooleanField(default=False)),
                ('can_override_insurance', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_counsellor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='RC001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desk_location', models.CharField(blank=True, help_text='Eg: Main Entrance', max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('can_access_billing', models.BooleanField(default=True)),
                ('can_modify_patient_records', models.BooleanField(default=False, help_text='Usually restricted to medical staff')),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrarProfile',
        ),
    ]
