# Generated by Django 5.2.12 on 2026-03-25 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_clinicalcounsellorprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
