# Generated by Django 5.2.12 on 2026-03-27 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 11, 55, 6, 715080, tzinfo=datetime.timezone.utc)),
        ),
    ]
