# Generated by Django 5.2.12 on 2026-03-30 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 9, 30, 40, 591804, tzinfo=datetime.timezone.utc)),
        ),
    ]
