# Generated by Django 5.2.12 on 2026-03-30 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 10, 4, 41, 891377, tzinfo=datetime.timezone.utc)),
        ),
    ]
