# Generated by Django 5.2.12 on 2026-03-30 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='can_register_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='can_schedule_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 10, 38, 51, 429544, tzinfo=datetime.timezone.utc)),
        ),
    ]
