# Generated by Django 5.2.12 on 2026-03-30 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_receptionistprofile_can_register_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalcounsellorprofile',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 11, 8, 13, 241139, tzinfo=datetime.timezone.utc)),
        ),
    ]
