# Generated by Django 5.2.12 on 2026-03-30 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_clinicalcounsellorprofile_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalcounsellorprofile',
            old_name='department_head',
            new_name='is_department_head',
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 11, 9, 5, 645920, tzinfo=datetime.timezone.utc)),
        ),
    ]
