# Generated by Django 5.2.12 on 2026-03-30 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_department_head_clinicalcounsellorprofile_is_department_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 30, 11, 42, 32, 419130, tzinfo=datetime.timezone.utc)),
        ),
    ]
