# Generated by Django 5.2.12 on 2026-04-13 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embryologistprofile',
            name='can_perform_biopsy',
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 13, 11, 7, 40, 786300, tzinfo=datetime.timezone.utc)),
        ),
    ]
