# Generated by Django 5.2.12 on 2026-04-23 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_embryologistprofile_can_perform_biopsy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 12, 33, 16, 253011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='GynaecologistProfile',
        ),
    ]
