# Generated by Django 5.2.12 on 2026-04-27 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_loginauditlog_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 27, 11, 56, 15, 184941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REC', 'Receptionist'), ('CCO', 'Clinical Counsellor'), ('FCO', 'Financial Counsellor'), ('END', 'Reproductive Endocrinologist'), ('GYN', 'Gynaecologist'), ('ANE', 'Anesthesiologist'), ('EMB', 'Embryologist'), ('NUR', 'Nurse'), ('PHA', 'Pharmacist'), ('TEC', 'Lab Technician'), ('AND', 'Andrology Lab Technician'), ('PAT', 'Patient'), ('HRM', 'HR Manager'), ('ADM', 'Admin')], default='PAT', max_length=3),
        ),
    ]
