# Generated by Django 5.2.13 on 2026-04-29 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_loginauditlog_last_seen_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 5, 58, 13, 103454, tzinfo=datetime.timezone.utc)),
        ),
    ]
