# Generated by Django 5.2.13 on 2026-04-29 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 9, 42, 7, 872411, tzinfo=datetime.timezone.utc)),
        ),
    ]
