# Generated by Django 5.2.13 on 2026-04-30 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 6, 26, 20, 986419, tzinfo=datetime.timezone.utc)),
        ),
    ]
