# Generated by Django 5.2.13 on 2026-05-04 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embryologistprofile',
            name='is_lab_director',
        ),
        migrations.AddField(
            model_name='embryologistprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialcounsellorprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 9, 20, 18, 270090, tzinfo=datetime.timezone.utc)),
        ),
    ]
