# Generated by Django 5.2.13 on 2026-05-04 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_embryologistprofile_is_lab_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embryologistprofile',
            name='can_perform_biopsy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 12, 28, 13, 228099, tzinfo=datetime.timezone.utc)),
        ),
    ]
