# Generated by Django 5.2.13 on 2026-05-05 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_embryologistprofile_can_perform_biopsy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 4, 35, 21, 600546, tzinfo=datetime.timezone.utc)),
        ),
    ]
