# Generated by Django 5.2.13 on 2026-05-05 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='anesthesiologistprofile',
            name='edit_anesthesia_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anesthesiologistprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 8, 44, 51, 429950, tzinfo=datetime.timezone.utc)),
        ),
    ]
