# Generated by Django 5.2.13 on 2026-05-06 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 10, 12, 44, 376461, tzinfo=datetime.timezone.utc)),
        ),
    ]
