# Generated by Django 5.2.13 on 2026-05-12 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_loginauditlog_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 12, 11, 15, 33, 552960, tzinfo=datetime.timezone.utc)),
        ),
    ]
