# Generated by Django 5.2.13 on 2026-05-12 11:15

import django.db.models.deletion
import emr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_patientprofile_treatment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('DIAGNOSIS', 'Diagnosis'), ('PRESCRIPTION', 'Prescription'), ('LAB_RESULT', 'Lab Result'), ('SCAN', 'Scan / Ultrasound'), ('PROCEDURE', 'Procedure Note'), ('CYCLE', 'Treatment Cycle'), ('NURSING_NOTE', 'Nursing Note'), ('PHARMACY_NOTE', 'Pharmacy Note'), ('ANDROLOGY_NOTE', 'Andrology Note'), ('COUNSELLING_NOTE', 'Counselling Note'), ('OTHER', 'Other')], default='CONSULTATION', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emr_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_records', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(blank=True, help_text='e.g. Pre-IVF, Emotional Support, Outcome', max_length=100)),
                ('concerns_raised', models.TextField(blank=True)),
                ('advice_given', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_note', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('examination', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AndrologyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(blank=True, help_text='e.g. Semen, Biopsy', max_length=100)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('concentration', models.CharField(blank=True, help_text='e.g. 15 million/mL', max_length=50)),
                ('motility_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('morphology_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dna_fragmentation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('who_criteria', models.CharField(blank=True, help_text='e.g. WHO 2021', max_length=20)),
                ('impression', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, help_text='Upload andrologyy report PDF', null=True, upload_to=emr.models.emr_upload_path)),
                ('report_image', models.ImageField(blank=True, help_text='Upload andrology report PDF', null=True, upload_to=emr.models.emr_upload_path)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andrology_note', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, help_text='Upload lab report pdf', null=True, upload_to=emr.models.emr_upload_path)),
                ('report_image', models.ImageField(blank=True, help_text='Upload  lab report image (JPG,PNG)', null=True, upload_to=emr.models.emr_upload_path)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PREV_RECORD', 'Previous Medical Record'), ('DISCHARGE', 'Discharge Summary'), ('PRESCRIPTION', 'Old Precription'), ('LAB_REPORT', 'Old Lab Report'), ('SCAN', 'Old Scan'), ('REFERRAL', 'Referral Letter'), ('OTHER', 'Other')], default='PREV_RECORD', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=emr.models.medical_history_upload_path)),
                ('notes', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, help_text='Date of the original document', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_documents', to='patients.patientprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_bp', models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=20)),
                ('vital_pulse', models.CharField(blank=True, help_text='e.g. 72bpm', max_length=20)),
                ('vital_temp', models.CharField(blank=True, help_text='e.g. 98.6 F', max_length=20)),
                ('vital_spo2', models.CharField(blank=True, help_text='e.g. 99%', max_length=20)),
                ('vital_weight', models.CharField(blank=True, help_text='e.g. 62kg', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('medications_given', models.TextField(blank=True, help_text='Medications administered during shift')),
                ('instructions_given', models.TextField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_note', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed_items', models.TextField(blank=True, help_text='List of medications dispensed')),
                ('batch_numbers', models.TextField(blank=True)),
                ('dispensing_notes', models.TextField(blank=True)),
                ('counselling_given', models.TextField(blank=True, help_text='Patient counselling notes at dispensing')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_note', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, help_text='e.g. Oral, IM, IV', max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(help_text='e.g. OPU, Emmbryo Transfer, ICSI', max_length=200)),
                ('details', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_performed', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(blank=True, help_text='e.g. TVS USG, Abdominal USG', max_length=100)),
                ('findings', models.TextField(blank=True)),
                ('follicle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('endometrium', models.CharField(blank=True, help_text='e.g. 9mm trilaminar', max_length=100)),
                ('impression', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload scan image (JPG,PNG)', null=True, upload_to=emr.models.emr_upload_path)),
                ('report_file', models.FileField(blank=True, help_text='Upload scan report PDF', null=True, upload_to=emr.models.emr_upload_path)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='emr.emrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('IVF', 'In Vitro Fertilization(IVF) Cycle'), ('IUI', 'IntraUterine Insemination(IUI) Cycle'), ('FET', 'Frozen Embryo Transfer(FET)'), ('ICSI', 'ICSI Cycle'), ('OI', 'Ovulation Induction'), ('IVM', 'In Vitro Maturation'), ('EGG_FREEZE', 'Egg Freezing'), ('EMBRYO_FREEZE', 'Embryo Freezing'), ('SPERM_FREEZE', 'Sperm Freezing'), ('PGT', 'PGT Cycle'), ('OTHER', 'Other')], max_length=20)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='ONGOING', max_length=20)),
                ('eggs_retrieved', models.PositiveIntegerField(blank=True, null=True)),
                ('eggs_fertilized', models.PositiveIntegerField(blank=True, null=True)),
                ('embryos_formed', models.PositiveIntegerField(blank=True, null=True)),
                ('embryos_transfered', models.PositiveIntegerField(blank=True, null=True)),
                ('embryos_frozen', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle', to='emr.emrrecord')),
            ],
        ),
    ]
