# Generated by Django 5.2.13 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdepartmentassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
