# Generated by Django 5.2.12 on 2026-03-14 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='HR001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('managed_depts', models.CharField(blank=True, help_text='Eg: Clinical, Laboratory,..', max_length=200)),
                ('can_approve_leaves', models.BooleanField(default=True)),
                ('can_view_salaries', models.BooleanField(default=True)),
                ('can_terminate_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
