# Generated by Django 5.2.12 on 2026-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanagerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
