# Generated by Django 5.2.12 on 2026-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hrmanagerprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanagerprofile',
            name='managed_depts',
            field=models.CharField(blank=True, help_text='Eg: Clinical, Laboratory,..', max_length=200, null=True),
        ),
    ]
