# Generated by Django 5.2.12 on 2026-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_hrmanagerprofile_managed_depts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanagerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
