# Generated by Django 5.2.12 on 2026-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_hrmanagerprofile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanagerprofile',
            name='can_edit_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrmanagerprofile',
            name='can_generate_payslips',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrmanagerprofile',
            name='can_update_documents',
            field=models.BooleanField(default=True),
        ),
    ]
