# Generated by Django 5.2.13 on 2026-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_hrmanagerprofile_can_edit_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanagerprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
