# Generated by Django 5.2.13 on 2026-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('IVF', 'In Vitro Fertilization(IVF)'), ('IUI', 'IntraUterine Insemination(IUI)'), ('FET', 'Frozen Embryo Transfer(FET)'), ('ICSI', 'IntraCytoplasmic Sperm Injection(ICSI)'), ('OI', 'Ovulation Induction'), ('IVM', 'In Vitro Maturation'), ('EGG_FREEZE', 'Egg Freezing'), ('EMBRYO_FREEZE', 'Embryo Freezing'), ('SPERM_FREEZE', 'Sperm Freeze'), ('PGT', 'Preimplantation Genetic Testing(PGT)'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
