# Generated by Django 5.2.13 on 2026-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistprofile',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
