# Generated by Django 5.2.12 on 2026-03-14 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('donor_code', models.CharField(blank=True, editable=False, help_text='eg: DON001', max_length=10, unique=True)),
                ('donor_type', models.CharField(blank=True, choices=[('EGG', 'Egg Donor'), ('SPERM', 'Sperm Donor'), ('EMBRYO', 'Embryo Donor')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('height_cm', models.PositiveIntegerField(blank=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True)),
                ('eye_color', models.CharField(blank=True, max_length=30)),
                ('hair_color', models.CharField(blank=True, max_length=30)),
                ('skin_tone', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('genetic_screening_cleared', models.BooleanField(default=False)),
                ('screening_expiry_date', models.DateField(blank=True, help_text='Infections screening usually expire every 6 months.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('donor_partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embryo_donor_partner', to='donor.donorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
