# Generated by Django 5.2.12 on 2026-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
