# Generated by Django 5.2.12 on 2026-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donorprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='eye_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='hair_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
