# Generated by Django 5.2.12 on 2026-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donorprofile_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='compensation_packagr',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
