# Generated by Django 5.2.12 on 2026-04-23 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GynaecologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='DR001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('total_egg_retrievals', models.PositiveIntegerField(blank=True, default=0)),
                ('medical_license_no', models.CharField(blank=True, max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gynaec_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
