# Generated by Django 5.2.12 on 2026-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gynaecology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gynaecologistprofile',
            name='total_egg_retrievals',
        ),
        migrations.AddField(
            model_name='gynaecologistprofile',
            name='can_assist_ivf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gynaecologistprofile',
            name='can_perform_egg_retrieval',
            field=models.BooleanField(default=False),
        ),
    ]
