# Generated by Django 5.2.13 on 2026-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gynaecology', '0002_remove_gynaecologistprofile_total_egg_retrievals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gynaecologistprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
